root = "."
tmp_dir = "tmp/"

[build]
  cmd = "powershell.exe -File util/build_frontend.ps1"
  bin = "simple"
  include_ext = ["js", "css", "html", "gox"]
  exclude_dir = ["backend", "tmp"]
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"