root = "."
tmp_dir = "tmp/"

[build]
  cmd = "sh util/build_frontend.sh"
  bin = "simple"  # Adjust if necessary. This field needs to reflect what your build command outputs or expects.
  include_ext = ["js", "css", "html", "gox"]
  exclude_dir = ["backend", "tmp"]
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
